apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: manifest-generate-paths-file-not-exist-example
  namespace: argocd
  annotations:
    argocd.argoproj.io/manifest-generate-paths: "some-other-path;/examples/helm/values/some-other-file.yaml"
spec:
  project: default
  destination:
    name: in-cluster
    namespace: default
  sources:
    - repoURL: https://github.com/dag-andersen/argocd-diff-preview
      ref: local-files
    - path: examples/helm/charts/myApp
      repoURL: https://github.com/dag-andersen/argocd-diff-preview
      helm:
        valueFiles:
          - $local-files/examples/helm/values/filtered.yaml
        valuesObject:
          replicaCount: 5
